version: '3'
services:
    xvision-frontend:
        image: xvision-ui
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes:
            - "./frontend:/angular"
            - "ang_node_vol:/angular/node_modules"
    xvision-backend:
        image: xvision-api
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - "./backend:/backend"
            - "back_node_vol:/backend/node_modules"
volumes:
  ang_node_vol:
  back_node_vol: