# Get Alpine Linux
FROM node:16.10.0-alpine AS node

# Install bash, sudo, and git
RUN apk add bash \
    sudo \
    git

# change working directory
WORKDIR /angular

# copy package.json
COPY package.json ./

# Install Angular CLI
RUN npm install -g @angular/cli@14.2.0

# install dependencies
RUN npm install --force

# Export port 4200
EXPOSE 4200

# start app
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
